version: "3.8"

services:
  php:
    image: mustakimkhan/php-tp1
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/

  db:
    image: postgres:9.6.24-alpine3.15
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database

  adminer:
    image: adminer:4.8.1
    ports:
     - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
